### ISSUE TITLE
Experiment Rules, to be replaced by game logic

### ISSUE THREAD

**Issue by luttje** [luttje/gmod-experiment-redux#15]
The intention for the new version of Experiment is to have as few rules as possible. Instead making negative gameplay impossible or unattractive.

I have here a copy of the old Experiment rules. These are from when we ran it over a decade ago. *Pardon any crude language*. Some rules will remain (like the no hacking and rules against harassment). We'll find ways to moderate this effectively. For example I'm thinking of using AI to flag offensive chats to be moderated by a human moderator.

In between the rules I'll form task lists, to track how much I feel we've mitigated with game mechanics.

> <div align="center">
>
> ## ||VM|| Experiment 4 - Rules
>
> These are the new rules to keep Experiment excited but enjoyable. If you are caught constantly killing people for the most insane reasons or ruining gameplay in general, you will be permanently banned.
>  
> Although there's only 16 rules, you should use common sense to think of what you can and can not do.
>
> </div>
> 
> _____________________________________________
> 
> 1. Any abuse or exploitation of the script, game or map will result in a permanent ban which can NOT be disputed.
> This includes but is not limited to: Duping, map exploiting, aimbotting, using glitches.
> You are allowed to jump upto place you couldn't go without acrobatics, but as soon as:
>     - You are able to jump off the map
>     - Can see parts of the map you aren't supposed to see (can see the bottom of the map)
>     - Can see through parts that can't be seen through from the other side.
> You are 'glitching', leave that spot or you'll be banned. 

- [ ] Restrict where players can get, so they can't get outside of the map (or to other unfair places) #78 
- [x] The rule against duping, exploiting and hacking stays, find a way to effectively communicate it to new players

> 2. What happens in character stays in character.
> Although experiment is pushed against the thin border between deathmatch and RP, you may not harass or insult people OOCly.

- [ ] Implement a way to log chats to an external tool, for moderation by AI and verification by humans #79
- [x] Implement a way to transcribe voice chat for moderation, see also: [`gmod-voice-chat-recorder`](https://github.com/luttje/gmod-voice-chat-recorder)
- [x] This rule on harassment needs to be refined, but stays in some form. The part about 'experiment is pushed against the thin border between deathmatch and RP' is irrelevant. Find a way to effectively communicate it to new players

> 3. You may not kill/attack/provoke people at spawn and you may not run back into spawn.
> Spawn is protected now, as soon as you leave it you wont be able to enter it again. If you glitch in though, you will be permanently banned.

- [x] Implement multiple spawn points with restrictions, see #17

> 4. You may not use props to climb or surf to places outside of the map or try and kill people with them.
> Items also count as props.

- [x] Make props that players hold in their hands not do damage: [Helix handles this](https://github.com/NebulousCloud/helix/blob/5bbfad40e4dea1eec3d02f74ef55530909db73a2/gamemode/core/hooks/sv_hooks.lua#L218-L219)
- [x] Players can still throw props hard, but this seems fine to me. If it does too much damage I'll lower it. Let's keep an eye out for abuse.
- [x] Restrict building mechanics to a form that is harder to abuse. #16 fixes prop surfing
- [x] Come up with a sensible way to how we can restrict prop climbing to places outside the map. _For example: props may never be placed higher than Z units above a floor surface._

> 5. You may only use a single layer of props to block of an area.
> Meaning, if someone wants to get from A to B, there has to be at least 1 way to get there in which only 1 prop will have to be destroyed.

- [x] Mitigated with Siege Surge buff in #16

> 6. You may NOT kill/tie/raid/attack people without a reason.
> These are some valid reasons:
>     - Someone is pointing a gun at you;
>     - You can take revenge if they killed you or robbed you earlier;
>     - Someone is showing wealth(Wearing a Sturdy/Strike/etc uniform and higher; or carrying a raging bull revolver and higher)
>     - Someone is in your alliances territory trying to either damage your alliance members or/and territory
> 
>     You can not kill characters for the colour of their skin, you may not punch them and you may not tie them for just being black or white. 

- [x] Discourage negative behavior through negative buffs
- [x] Promote friendly behavior, e.g: #11 

> 7. You may not insult any member/(super) admin/moderator of the community Out-Of-Character.
> You may insult these people's character IC.

- [x] Consider if this doesn't fall under harassment (even if In-Character). In my experience it was hard for players to separate the game from real life, so might be easier (for the AI moderation too) to just ban all harassment.

> 8. You may not disconnect to avoid being tied, losing something or dying.
> This also applies when your PC/Internet Connection fails. Doing so will result in you losing all your items(automatically).

- [x] Re-implement the system where the player loses everything if they disconnect

> 9. You may not keep characters tied/imprisoned for longer than 30 minutes. After a 30 minute imprisonment you can kill the character.
> This does not mean, that after you killed a character you can look it up and imprison it again for 30 minutes. (If the character returns, trying to take revenge, you are free to capture it again)

- [x] Discourage players keeping someone imprisoned for a long time #49
- [x] Provide meaningful ways for players to escape imprisonment #49

> 10. Respect the script and it's players.
> To many members, Experiment is more than just a Deathmatch script with some roleplaying features. You should respect that and should at least try to roleplay as much as you can.
> E.g: when someone puts a gun to your head (wearing full exo) asking you where that person with the dark brown hair went. You tell them they went *Anywhere* and cower like hell.
> On the other hand, if you are wearing full exo and you see someone wearing nothing at all, dont try and provoke the person.

- [x] Scrapping this rule since it's incredibly hard to moderate and enforce. I'm not going to spend time teaching people how to roleplay in video games. I also don't want to restrict how they want to roleplay. If they feel like standing up against someone way stronger than them, have at it and live with the in-game consequences. I'd much rather spend time making fun game mechanics than organizing an admin team that has to keep an eye out for this.
- [x] Promote positive behavior through game mechanics, like #11 

> 11. Do not whore achievements or attributes.
> Don't do it.

- [x] Disable all attribute training through running, jumping, punching, etc.
- [ ] Implement training of attributes through intentional game mechanics #8

> 12. Do not use props that can be seen through on only 1 side.
> There are several props which have 1 side with texture and the other side without, using these will get you banned.

- [x] Restrict which props players can build #16

> 13. Do not use binds to spam items such as Health Kits or Kevlar.
> This creates an unfair advantage, in the way that a player can effectively be invincible using this method, we hope to remedy this in a future update.

- [x] Implement de-buffs that reduce the effectiveness of these types of items when used in quick succession.
- [ ] Implement a quick-bind system so players that don't know how to use the game console can also get access to easy item use bindings #77 

> 14. Do not revive the same person more than once to gain all their money or items.
> You may still revive friends to keep them alive in a battle, but you may no longer revive your enemies more than once.

- [x] Limit how often a player can be revived in a period of time (e.g: with a de-buff)

> 15. Do not trade items/money with your other characters.
> You may not transfer in-game goods to other characters, if you do, you (and if someone helped you too) will be banned.

- [x] This is restricted by Helix in some way. I'm not bothered by players trying to circumvent this, I don't see the the advantage of managing multiple characters, there shouldn't be an advantage. 

> 16. On the rp_apocalypse map you may not block of the access to the underground area.
> You may not block off the locker in there, the elevator or the giant shaft. When you're at the bottom of the elevator or shaft you may block it off, but only if you're going to use the entire area for RP/faction purposes!

- [x] We won't play on rp_apocalypse and even if we did this would be mitigated by #16.

If anyone has ideas for how to prevent things listed here with in-game mechanics, feel free to brainstorm in the replies below.

**Comment by luttje** [comment]
Closing this in favor of the individually created issues (all linked above)
