### ISSUE TITLE
Finish external moderation system

### ISSUE THREAD

**Issue by luttje** [luttje/gmod-experiment-redux#79]
I've setup an 'external moderation' system in order to keep administration efforts achievable for a small team. This is what it looks like at the moment:

![screenshot](https://github.com/luttje/gmod-experiment-redux/assets/2738114/275e10cc-aa91-4014-b908-7331712949d9)

## 📃 Tasks

Here's the task list for this system.

- [x] Send chat logs to the moderation system for verification
- [x] Record and transcribe voice chat, then send that to the moderation system
- [x] Let moderators register
- [x] Let moderators mark chats as 'safe'
- [x] Let moderators listen to transcribed audio files, to check if the transcription is correct (it's transcribed on-device, which can be terrible)
- [x] Marking chats as 'safe' removes the related audio file to free up space
- [ ] Test what happens when a lot of players spam chat
- [ ] Test what happens when a lot of players spam voice chat (probably bad things, needs fixing)
- [x] Let moderators impose sanctions from the moderation panel
- [x] Add 'warning' as a sanction that is shown the a player in the server (or when they connect)
- [x] Load sanctions when player connects, to see if they should be: muted, kicked or banned
- [x] Organize sanction escalation protocol, e.g: `warn -> mute -> kick -> temporary ban -> at most a year-long ban`
- [x] Make the tool better accessible on mobile devices
- [x] Add <s>quick/bulk actions to quickly moderate, perhaps even</s> a swipe left/right type of UI for mobile
- [x] Add algorithms to automatically flag questionable chats for closer inspection (maybe use an LLM if the fuzzy search for naughty words doesn't suffice)
- [ ] When users request their data be deleted, anonymize their data in the moderation system (so sanctions can be upheld, whilst respecting privacy) #124 
- [ ] <s>Add way to sanction in-game, and have that recorded in external moderation tool</s> Nvm, just have the tool open on a second monitor instead
