### ISSUE TITLE
🗺 exp_c18_v1 (customized rp_c18)

### ISSUE THREAD

**Issue by luttje** [luttje/gmod-experiment-redux#96]
I've been toying around with modifying rp_c18 (based on a vmf of rp_c18_new_rv11 that is available online). It's a nice change from fixing bugs for weeks on end and gives me a deserved break from coding.

I'm locked on using c18 as a base for nostalgic reasons, however the Combine and other HL2 atmosphere in it is not something that works for Experiment. I've been changing Combine models and materials to regular assets available in HL2.

A bit of the story that will be told through locations in exp_c18_v1:
> The Guardian Corporation (name not necessarily final) attempted to create some sort of crowd-control AI. This city seems to be a testing facility built by the corporation. We're not sure what happened, but everyone related to the corporation has ceased to exist, and the test subjects have become enslaved to the whims of the AI.

## Task list

- [ ] #78
- [ ] Replace dead-end streets with more creative boundaries (currently combine walls)
- [x] Connect slums alley (next to the restaurant) to the hospital street (something I've always wanted to do)
- [x] Replace combine elevators with freight elevators
- [x] Remove Breen office (replaced with flats)
- [ ] Replace all combine posters/advertisements
- [ ] Add new 3D skybox with distant mountains/nature (that we can possibly connect to in the future, @Nelaif)

## 📸 Preview

_It seems an accident involving a tank truck and passing train on a bridge caused this street to become impassable._
![20240511105056_1](https://github.com/luttje/gmod-experiment-redux/assets/2738114/25f8f04d-546b-4038-9335-6ec791486b4d)

_A light blinks at the top floor of the Guardian Corporation office building (Nexus), what could it be?_

https://github.com/luttje/gmod-experiment-redux/assets/2738114/c7aba015-8913-4444-9697-a95cd6a7826d

_Some of the new locations:_

https://github.com/luttje/gmod-experiment-redux/assets/2738114/e3f27ab2-90f3-4e32-b2d2-54f4f4889258

**Comment by Nelaif** [comment]
👏👏👏👏👏 super goed!

**Comment by utaysi** [comment]
> Remove Breen office (replaced with flats)

Nooo. I mean it makes more sense gameplay wise. I am just being emotional 😅 

The changes & ideas seem very nice. Good job :)

**Comment by luttje** [comment]
I'm sorry for the loss of Breen's office @utaysi 😉 What did you like about it? Maybe I can find a different place where a similar vibe makes more sense.

**Comment by utaysi** [comment]
I liked the skill jump on the panel in the main room to the left, you could climb to reach this hidden floor above where you could hide your generators. I know it is not an intentional spot by the mapper, but most veterans knew the spot and discovering it for the first time made most people happy I believe :p It was also a nice accomplishment when you increased your acrobatics the climb would be easier each time.

So perhaps there could be intentional semi-hidden and/or skill-climb spots in the future. I believe they always make maps more interesting.

**Comment by luttje** [comment]
> I liked the skill jump on the panel in the main room to the left, you could climb to reach this hidden floor above where you could hide your generators. I know it is not an intentional spot by the mapper, but most veterans knew the spot and discovering it for the first time made most people happy I believe :p It was also a nice accomplishment when you increased your acrobatics the climb would be easier each time.
> 
> So perhaps there could be intentional semi-hidden and/or skill-climb spots in the future. I believe they always make maps more interesting.

Good idea, it would make acrobatics more interesting!

**Comment by luttje** [comment]
Early preview of the map if anyone's interested: [**🗺 Download exp_c18_v1_alpha028.zip**](https://github.com/luttje/gmod-experiment-redux/files/15299841/exp_c18_v1_alpha028.zip)

Simply unpack the `exp_c18_v1_alpha028.bsp` into your `GarrysMod/garrysmod/maps` directory, then open Garry's Mod and start a singleplayer game on the map (it'll likely be categorized under 'Other').

The map only uses HL2 and custom content and the custom content should be packed into the map. This all means the map should work out of the box. However if you still see any errors or missing textures let me know and I'll find out what I did wrong.

**Comment by luttje** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=3250002134
